name: runwayml_flutter
description: "A Flutter package that provides a Dart wrapper for the RunwayML API, enabling integration of AI-generated content into Flutter apps."
version: 0.0.7
homepage: https://github.com/FlutterWiz/runwayml_flutter
issue_tracker: https://github.com/FlutterWiz/runwayml_flutter/issues
topics: [runwayml-flutter, runway, runwayml]
funding: [https://github.com/sponsors/FlutterWiz]

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: The runwayml_flutter package logo.
    path: screenshots/logo.png
